// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUbheDp5A-znJfQM7Ecqg6unv9Ax9s6vQ',
    appId: '1:563754587366:web:98d218777e394bcf425727',
    messagingSenderId: '563754587366',
    projectId: 'run-tracker-c16ee',
    authDomain: 'run-tracker-c16ee.firebaseapp.com',
    databaseURL: 'https://run-tracker-c16ee-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'run-tracker-c16ee.firebasestorage.app',
    measurementId: 'G-VSYXH9LGTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUbheDp5A-znJfQM7Ecqg6unv9Ax9s6vQ',
    appId: '1:563754587366:android:98d218777e394bcf425727',
    messagingSenderId: '563754587366',
    projectId: 'run-tracker-c16ee',
    authDomain: 'run-tracker-c16ee.firebaseapp.com',
    databaseURL: 'https://run-tracker-c16ee-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'run-tracker-c16ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUbheDp5A-znJfQM7Ecqg6unv9Ax9s6vQ',
    appId: '1:563754587366:ios:98d218777e394bcf425727',
    messagingSenderId: '563754587366',
    projectId: 'run-tracker-c16ee',
    authDomain: 'run-tracker-c16ee.firebaseapp.com',
    databaseURL: 'https://run-tracker-c16ee-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'run-tracker-c16ee.firebasestorage.app',
    iosBundleId: 'com.example.runningTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUbheDp5A-znJfQM7Ecqg6unv9Ax9s6vQ',
    appId: '1:563754587366:macos:98d218777e394bcf425727',
    messagingSenderId: '563754587366',
    projectId: 'run-tracker-c16ee',
    authDomain: 'run-tracker-c16ee.firebaseapp.com',
    databaseURL: 'https://run-tracker-c16ee-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'run-tracker-c16ee.firebasestorage.app',
    iosBundleId: 'com.example.runningTracker',
  );
}